INSERT INTO types (name) VALUES ('chikuwabu');
INSERT INTO types (name) VALUES ('egg');
INSERT INTO types (name) VALUES ('squid');
INSERT INTO types (name) VALUES ('daikon');
INSERT INTO types (name) VALUES ('fish ball');
INSERT INTO types (name) VALUES ('potato');
INSERT INTO types (name) VALUES ('taro');
INSERT INTO types (name) VALUES ('chikuwa');
INSERT INTO types (name) VALUES ('konnyaku');
INSERT INTO types (name) VALUES ('shirataki');
INSERT INTO types (name) VALUES ('fried fish ball');
INSERT INTO types (name) VALUES ('tofu pouch');
INSERT INTO types (name) VALUES ('tofu fritter');
INSERT INTO types (name) VALUES ('hanpen');
INSERT INTO types (name) VALUES ('kombu');
INSERT INTO types (name) VALUES ('gobou');